### PR TITLE
Corrected BIOS CRC checking by Holly to unlock G1

### PR DESCRIPTION
**Pull request by DC-SWAT**
Hi. This fix needed for boot homebrews if DC used custom BIOS.

### CODE REVIEW

**Comment by p1pkin** [comment]
errm.. SWAT, it seems you still didn't get how this CRC protection works ;)
on non-modded bios if((*(uint16 *)0xa0000000) == 0xe6ff) will f*ckup current checksum which lead to system lock, because 5f74e4 was already written by bios, so HOLLY sum all read values.

in my opinion its better to leave it as is or use original Mil-CD way instead, i.e.:
for(p = 0x1000 / sizeof(bios[0]); p < 0x4300 / sizeof(bios[0]); p++) (void)bios[p]; 
with no any *react = xxxxxxx,

so the main idea:
- in the case of stock DC bioses: unlock required, at 5f74e4 already written 42FE, so we read values and unlock G1 IDE.
- in the case of custom BIOSes like JapaneCake's: unlock is not required, 5f74e4 was not written by bios, so this routine will do just dummy read.

however, this will not work with some customized BIOSes, which for some odd reason write 5f74e4 before start Mil-CD executables, and contain some customized data in 1000h-4300h (ie syscalls) area.

**Comment by ljsebald** [comment]
Was going to point out that this was broken... But obviously that's already been pointed out.

**Comment by DC-SWAT** [comment]
OMG sorry, I know, just forget about CD, I don't use it for a long time.
It's works only if binary executed directly, but broken boot from CD.
Need another way...

**Comment by p1pkin** [comment]
its not only about glitchy way, its in general, there is already mess with G1 IDE unlock in DC software, so I think its bad idea to make even more of that mess.

**Comment by DC-SWAT** [comment]
With it need to do something, current code is not actual.

**Comment by DC-SWAT** [comment]
btw p1pkin, my first code works in RC4 (it's boot from CD and GDEMU)

**Comment by p1pkin** [comment]
Re: [ljsebald/KallistiOS] Corrected BIOS CRC checking by Holly to unlock G1 (#3)


that bios was used stock or some custom ?





btw p1pkin, my first code works in RC4 (it's boot from CD and GDEMU)
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.





-- 
with best regards
                     MetalliC        mailto:0vetal0@gmail.com

**Comment by DC-SWAT** [comment]
Both.

**Pull request closed without merging**
